spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mybatistest
    driver-class-name: org.h2.Driver
    username: sa
    password:

#mybatis
mybatis:
  type-aliases-package: board.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    board.repository.mybatis: trace